spring:
  application:
    name: collageapi

  datasource:
    username: abhishek
    password: abhishek9773
    url: jdbc:mysql://localhost:3306/collageapi
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
